import type { InvoiceRequest } from './types'

export const MOCK_INVOICES: InvoiceRequest[] = [
  {
    id: 'INV-2026-001',
    exporter: 'Anatolia Olive Co.',
    exporterLocation: 'Izmir, Turkey',
    exporterSector: 'Olive oil export',
    buyer: 'Berlin Gourmet GmbH',
    buyerCountry: 'Germany',
    amount: 50000,
    currency: 'USD',
    paymentTermDays: 60,
    advanceRate: 85,
    advanceAmount: 42500,
    status: 'Buyer Confirmed',
    riskLevel: 'Medium',
    confidenceScore: 72,
    documents: [
      { type: 'Commercial Invoice', fileName: 'invoice_berlin_gourmet_2026.pdf', hash: '0x8f3a...92b1', uploaded: true, uploadedAt: '2026-05-01' },
      { type: 'Purchase Order', fileName: 'po_berlin_gourmet_042026.pdf', hash: '0x2d7c...f4e9', uploaded: true, uploadedAt: '2026-05-01' },
      { type: 'Shipping Document', fileName: 'bl_ege_hamburg_051026.pdf', hash: '0x9a1b...30c7', uploaded: true, uploadedAt: '2026-05-02' },
      { type: 'Customs Declaration', fileName: 'customs_de_2026_0412.pdf', hash: '0x4f8e...77d2', uploaded: true, uploadedAt: '2026-05-02' },
      { type: 'Buyer Confirmation', fileName: 'buyer_conf_berlin_signed.pdf', hash: '0xb3c9...1a55', uploaded: true, uploadedAt: '2026-05-03' },
    ],
    createdAt: '2026-05-01',
  },
  {
    id: 'INV-2026-002',
    exporter: 'Ege Textile Studio',
    exporterLocation: 'Bursa, Turkey',
    exporterSector: 'Textile',
    buyer: 'Amsterdam Retail Partners',
    buyerCountry: 'Netherlands',
    amount: 28000,
    currency: 'USD',
    paymentTermDays: 45,
    advanceRate: 80,
    advanceAmount: 22400,
    status: 'Verified',
    riskLevel: 'Low',
    confidenceScore: 88,
    documents: [
      { type: 'Commercial Invoice', fileName: 'invoice_arp_may2026.pdf', hash: '0x5c2d...83a4', uploaded: true, uploadedAt: '2026-04-25' },
      { type: 'Purchase Order', fileName: 'po_amsterdam_retail_2026.pdf', hash: '0x7e9f...c112', uploaded: true, uploadedAt: '2026-04-25' },
      { type: 'Shipping Document', fileName: 'airway_bill_ams_2026.pdf', hash: '0x1b4a...90fe', uploaded: true, uploadedAt: '2026-04-26' },
      { type: 'Customs Declaration', fileName: 'nl_customs_042026.pdf', hash: '0x6d3c...45bb', uploaded: true, uploadedAt: '2026-04-26' },
      { type: 'Buyer Confirmation', fileName: 'buyer_conf_arp_signed.pdf', hash: '0xa2f7...28e3', uploaded: true, uploadedAt: '2026-04-27' },
    ],
    createdAt: '2026-04-25',
    attestationHash: '0x91c4...fa22',
  },
  {
    id: 'INV-2026-003',
    exporter: 'Cappadocia Foods',
    exporterLocation: 'Nevşehir, Turkey',
    exporterSector: 'Dried fruits',
    buyer: 'Dubai Fine Foods LLC',
    buyerCountry: 'UAE',
    amount: 75000,
    currency: 'USD',
    paymentTermDays: 90,
    advanceRate: 75,
    advanceAmount: 56250,
    status: 'Documents Uploaded',
    riskLevel: 'Medium',
    confidenceScore: 61,
    documents: [
      { type: 'Commercial Invoice', fileName: 'invoice_dubai_fine_2026.pdf', hash: '0x3e8b...f730', uploaded: true, uploadedAt: '2026-05-05' },
      { type: 'Purchase Order', fileName: 'po_dff_052026.pdf', hash: '0x9c4a...2d81', uploaded: true, uploadedAt: '2026-05-05' },
      { type: 'Shipping Document', fileName: 'bl_istanbul_dubai_2026.pdf', hash: '0x7f1e...bb43', uploaded: false },
      { type: 'Customs Declaration', fileName: '', hash: '', uploaded: false },
      { type: 'Buyer Confirmation', fileName: '', hash: '', uploaded: false },
    ],
    createdAt: '2026-05-05',
  },
  {
    id: 'INV-2026-004',
    exporter: 'Istanbul Machinery Parts',
    exporterLocation: 'Istanbul, Turkey',
    exporterSector: 'Industrial components',
    buyer: 'Milan Components SRL',
    buyerCountry: 'Italy',
    amount: 120000,
    currency: 'USD',
    paymentTermDays: 75,
    advanceRate: 85,
    advanceAmount: 102000,
    status: 'Funded',
    riskLevel: 'Low',
    confidenceScore: 91,
    documents: [
      { type: 'Commercial Invoice', fileName: 'invoice_milan_comp_2026.pdf', hash: '0x2b5f...e947', uploaded: true, uploadedAt: '2026-04-15' },
      { type: 'Purchase Order', fileName: 'po_milan_components_04.pdf', hash: '0x8d3a...1c60', uploaded: true, uploadedAt: '2026-04-15' },
      { type: 'Shipping Document', fileName: 'bl_istanbul_genova_2026.pdf', hash: '0x4e7b...92a3', uploaded: true, uploadedAt: '2026-04-16' },
      { type: 'Customs Declaration', fileName: 'it_customs_042026.pdf', hash: '0xf1c8...55d9', uploaded: true, uploadedAt: '2026-04-16' },
      { type: 'Buyer Confirmation', fileName: 'buyer_conf_milan_signed.pdf', hash: '0x6a2d...e814', uploaded: true, uploadedAt: '2026-04-17' },
    ],
    createdAt: '2026-04-15',
    attestationHash: '0x5Tq9...dA21',
    txHash: '0x9Lm2...xF44',
  },
]

export const PLATFORM_STATS = {
  verifiedVolume: 273000,
  avgDaysUnlocked: 58,
  platformFees: 2047,
  investorReturn: 8172,
}

export const RISK_SIGNALS = [
  { label: 'Buyer confirmed receipt', passed: true },
  { label: 'Documents match invoice amount', passed: true },
  { label: 'Payment term under 90 days', passed: true },
  { label: 'No duplicate invoice hash detected', passed: true },
  { label: 'Exporter has previous shipments', passed: false },
]
